default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV["ONKURO_NEW_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: onkuro_new_development
  host: localhost

test:
  <<: *default
  database: onkuro_new_test

production:
  primary: &primary_production
    <<: *default
    database: onkuro_new_production
    username: <%= ENV["ONKURO_USER"] %>
    password: <%= ENV["ONKURO_NEW_DATABASE_PASSWORD"] %>
    host: onkuro-db.c74m22q2ww83.ap-northeast-1.rds.amazonaws.com
    port: 3306
  cache:
    <<: *primary_production
    database: onkuro_new_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: onkuro_new_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: onkuro_new_production_cable
    migrations_paths: db/cable_migrate
